version: '3'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authbase
    restart: always

  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

